version: "3.9"

services:
  server:
    build:
      context: .
      network: host
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      # HOST: "192.168.0.100"
      HOST: "0.0.0.0"
      PORT: "5000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app:rw
    command: npm run dev
